### ISSUE TITLE
Error handler in wrapper hides breaks and hides real error

### ISSUE THREAD

**Issue by sdbondi** [feathersjs/express#13]
Hi @daffl 

The error handler for the service calls assumes that a hook will be received. This is not always the case, if you have a error (syntax or otherwise) in a hook the catch callback will receive an error. When it does `hook.error.message` will fail (cannot read message of undefined)

https://github.com/feathersjs/express/blob/master/lib/rest/wrappers.js#L77

Perhaps we should check if the hook is an instance of an error

Something like:

```javascript
.catch(hook => {
const error = hook instanceof Error ? hook : hook.error;
...
})

**Comment by daffl** [comment]
In which case won't it return a hook?

**Comment by daffl** [comment]
This should return a hook in every case so I'd still like to figure out when this is the case 😄

**Comment by sdbondi** [comment]
Ah I see :smile: hmm, I've since fixed my code and now cannot remember what caused hook to be an error. I've also tried in a small app to throw an error in a middleware, and various ways in a hook and can't reproduce it. It has happened a few times ("cannot read message of undefined" from the catch block) so when I can reproduce it I'll reopen this issue with the details - if it relates to feathers. 

Thanks for your help :smile:

**Comment by sdbondi** [comment]
@daffl I've since been able to reproduce this.

```
module.exports = {
after: [
ctx => { throw new Error('Break me') },
]
}
```
results in the above mentioned problem where the error is not wrapped in a hook. This does not happen for before. Using `"@feathersjs/express": "^1.1.1",`

**Comment by sdbondi** [comment]
Ah ha! So I when you have an error in an after hook AND then an error in your error hook, errors aren't caught for the error hooks and the above situation happens.

https://github.com/feathersjs/feathers/blob/master/lib/hooks.js#L108

[few minutes later...]

**RESOLVED**

Can confirm that upgrading to `v3.1.3` fixes it with this PR
https://github.com/feathersjs/feathers/pull/819

**Comment by daffl** [comment]
Yep, @MitMaro did some great digging and I think we were able to get all of those edge cases.
