### ISSUE TITLE
Error in error hook results in unhandled rejection

### ISSUE THREAD

**Issue by MitMaro** [feathersjs/express#21]
Related to #19 in that it has a similar error, but is triggered by a different mechanism.

### Steps to reproduce

Create an application with an application error hook that throws an error, and a single service that throws an error to trigger the hook. Call the endpoint with Curl.

#### Reduced test case

See gist: https://gist.github.com/MitMaro/1b6016902e8eb965c63c738c939b0731

```javascript
const feathers = require('@feathersjs/feathers');
const express = require('@feathersjs/express');
const app = express(feathers());
app.configure(express.rest());
app.hooks({
	error: () => {
		console.log('Throwing error in error hook');
		throw new Error('Simulated error');
	}
})
app.use('/myservice', {
	async find(data, params) {
		// trigger error hook
		throw new Error();
	},
});
app.listen(3030);
console.log('Feathers app started on 127.0.0.1:3030');

```

### Expected behavior

An error in an error hook should not show a warning about an unhandled promise, and there should be some response to the client. A `TypeError` caused by attempting to assign a property to `null` caused the issue in my project proper. 

### Actual behavior

A unhandled rejection warning is displayed, and no response occurs.

**Console 1**:

```shell
$ node index.js
Feathers app started on 127.0.0.1:3030
Throwing error in error hook
(node:23416) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'message' of undefined
(node:23416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Console 2**:
```shell
$ curl 127.0.0.1:3030/myservice
```

By adding a `unhandledRejection` handler:

```javascript
process.on('unhandledRejection', (reason, p) => {
	console.error('Unhandled Rejection');
	console.error(reason);
});
```

The following is returned:

```
Unhandled Rejection
TypeError: Cannot read property 'message' of undefined
    at service.(anonymous function).then.catch.hook (/Users/timoram/code/broken-project-test-cases/feathers-express-error/node_modules/@feathersjs/express/lib/rest/wrappers.js:79:46)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### System configuration

**Module versions** :
```shell
$ npm list --depth=0
feathers-express-error@1.0.0 /Users/timoram/code/broken-project-test-cases/feathers-express-error
├── @feathersjs/express@1.2.0
└── @feathersjs/feathers@3.1.1
```

**NodeJS version**:
```shell
$ npm --version
5.6.0
$ node --version
v8.9.4
```

**Operating System**:
```shell
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
```

**Browser Version**: N/A

**React Native Version**: N/A

**Module Loader**: N/A

**Comment by MitMaro** [comment]
This may be an error with `@feathersjs/feathers` and not `@feathersjs/express` but since the error stack is from this project I feel like it should be reported here.

**Comment by daffl** [comment]
Dang, I totally should've double checked that as well. The problem here is that the error hook chain in https://github.com/feathersjs/feathers/blob/master/lib/hooks.js#L110 only gets processed with a `.then` and not a `.catch` 😞

**Comment by daffl** [comment]
Alright, they should be all fixed now, thank you for bringing those up!

**Comment by MitMaro** [comment]
No problem! Thanks for the quick resolution on this and the related issue!
