### ISSUE TITLE
[Proposal] Allow multiple express middleware functions to be passed into `app.use`

### ISSUE THREAD

**Issue by eXigentCoder** [feathersjs/express#24]
By default in Express 4.x you can pass in multiple middleware functions as an array to `app.use`, [documentation link](https://expressjs.com/en/4x/api.html#app.use) this allows you to chain middleware functions together on a specific route path.

Currently according to the [Feathers documentation for `app.use`](https://docs.feathersjs.com/api/express.html#appusepath-servicemw) you can only supply one middleware function. Testing the following code reveals the docs are correct and only one function can be provided. 

```javascript
app.use('/will-throw-error', [
        function(req, res, next) {
            console.log('step 1');
            next();
        },
        function(req, res) {
            console.log('step 2');
            res.status(200).send('it worked');
        }
    ]);
```

I believe implementing this feature will help reduce confusion for people who are familiar with using express on its own and also aid in implementing third party modules into a persons `feathers.js` application using existing documentation. I personally encountered this while trying to add the [swagger-ui-express](https://github.com/scottie1984/swagger-ui-express) library.

**Comment by daffl** [comment]
Closed via #25
