### ISSUE TITLE
Question: How to handle JSON:API

### ISSUE THREAD

**Issue by EmirGluhbegovic** [feathersjs/express#26]
I came across a thread where it was recommended to try out using the hooks and also to open a new issue if anyone wants to inquire more.

Here I am :p,

There is a featherjs json-api npm package but it does not seem to be well-maintained and does not handle quite a lot of the spec.

I want to ask what are people's current solutions to being JSON:API compliant?

I am looking at another module: https://github.com/GaiamTV/transformalizer
Thinking of creating a hook adapter around that, thoughts?

Also there is another much more bulky plugin: https://github.com/ethanresnick/json-api
The way I can think of doing this is omitting the @feathers/mongoose plugins and instead placing the json-api middleware, i.e.:
Convert this:
```
// Initialize our service with any options it requires
  app.use('/users', createService(options));

// Get our initialized service so that we can register hooks and filters
const service = app.service('users');
```
To This:

```
 var Front = new API.httpStrategies.Express(
    new API.controllers.API(registry), 
    new API.controllers.Documentation(registry, {name: 'Example API'})
 );

// Initialize our service with any options it requires
  app.use("/:type(users))", Front.apiRequest);

// Get our initialized service so that we can register hooks and filters
  const service = app.service('users');
```

Would you have a recommended way of integrating that with feathers?
I would like to give the client the option of subscribing to websockets or just making simple requests.

Regards,
Emir

**Comment by daffl** [comment]
I have a feeling that the JSON API spec isn't used as much with Feathers so you may not get an answer to what people are currently using.

Transformalizer looks good and probably the nicer one to use with Feathers. The other one looks a little more heavy. Another way would also be picking up the work on the existing plugin.
