### ISSUE TITLE
FeathersJS app.use variables reset to constructor state

### ISSUE THREAD

**Issue by LilithVL** [feathersjs/express#30]
### Steps to reproduce
The code is as follows:
Feathers backend:

```
class Foo {

  constructor() {
    this.childProcess = {};
    this.bar = false;
  }
  get(id) {
    if (id === "start") {
       this.childProcess = spawn(baz);
       this.bar = true;
    }
    else if (id === "print") {
       console.log(this.childProcess);
  }

var foo = new Foo();
app.use('foo', foo);

```
Front-end:
```
axios.get("localhost:3030/foo/start");
```
### Expected behavior
The child program baz should be spawned, and stored inside the variable foo.
### Actual behavior
The child program is spawned. However, when logging from within the backend, foo is like the base constructor and when calling print from front-end, it logs foo properly.
The constructor is only called once.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
@feathersjs/express 1.2.2
**NodeJS version**:
v10.1.0
**Operating System**:
macOS High Sierra v10.13.4
**Browser Version**:
Google Chrome
Version 66.0.3359.181 (Official Build) (64-bit)
**React Native Version**:

**Module Loader**:
NPM 5.6.0

**Comment by daffl** [comment]
Could you provide a full example to reproduce in a GitHub repository? I am using things like this a lot in custom service and never had any problems.
